### ISSUE TITLE
TypeError: db.collection is not a function

### ISSUE THREAD

**Issue by kamaubrian** [mschwarzmueller/nodejs-basics-tutorial#4]
### Using the mongodb library version 3.1.1 Gives the above error while performing any of the database transactions
`**TypeError: db.collection is not a function**
    at /home/brian-kamau/WebstormProjects/Node_Js_Basics/08_mongo_db/routes/index.js:42:12
    at result (/home/brian-kamau/WebstormProjects/Node_Js_Basics/08_mongo_db/node_modules/mongodb/lib/utils.js:414:17)
    at executeCallback (/home/brian-kamau/WebstormProjects/Node_Js_Basics/08_mongo_db/node_modules/mongodb/lib/utils.js:406:9)
    at err (/home/brian-kamau/WebstormProjects/Node_Js_Basics/08_mongo_db/node_modules/mongodb/lib/operations/mongo_client_ops.js:285:5)
    at connectCallback (/home/brian-kamau/WebstormProjects/Node_Js_Basics/08_mongo_db/node_modules/mongodb/lib/operations/mongo_client_ops.js:240:5)
    at process.nextTick (/home/brian-kamau/WebstormProjects/Node_Js_Basics/08_mongo_db/node_modules/mongodb/lib/operations/mongo_client_ops.js:436:7)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
`

**Comment by jeypc** [comment]
In mongodb version >= 3, to access the correct object, you need to reference your database name. so your code should be

`router.get('/get-data', function(req, res, next) {
  var resultArray = [];
  mongo.connect(url, function(err, database) {
    assert.equal(null, err);
    var dbname = database.db('test');
    var cursor = dbname.collection('user-data').find();
    cursor.forEach(function(doc, err) {
      assert.equal(null, err);
      resultArray.push(doc);
    }, function() {
      database.close();
      res.render('index', {items: resultArray});
    });
  });
});`

**Comment by jeypc** [comment]
In mongodb version >= 3, to access the correct object, you need to reference your database name. so your code should be

```javascript
router.get('/get-data', function(req, res, next) {
  var resultArray = [];
  mongo.connect(url, function(err, database) {
    assert.equal(null, err);
    var dbname = database.db('test');
    var cursor = dbname.collection('user-data').find();
    cursor.forEach(function(doc, err) {
      assert.equal(null, err);
      resultArray.push(doc);
    }, function() {
      database.close();
      res.render('index', {items: resultArray});
    });
  });
});
```

https://stackoverflow.com/questions/43779323/typeerror-db-collection-is-not-a-function
